FROM clickhouse/clickhouse-server:23.8

RUN apt-get update \ 
    && apt-get install -y lsb-release curl
    
RUN curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc \
    && curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | tee /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update \ 
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18  mssql-tools18 \
    && echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc \
    && apt-get clean all

COPY odbc.ini /etc/odbc.ini